### ISSUE TITLE
ipa request

### ISSUE THREAD

**Issue by Shuopu** [crazypoo/PTChatGPT#5]
大佬能不能直接把ipa包发到release里啊，这边用虚拟机的Mac来build实在太崩溃了

**Comment by crazypoo** [comment]
> 大佬能不能直接把ipa包发到release里啊，这边用虚拟机的Mac来build实在太崩溃了

沒有證書build不了哦

**Comment by LunWhale** [comment]
> > 大佬能不能直接把ipa包发到release里啊，这边用虚拟机的Mac来build实在太崩溃了
> 
> 沒有證書build不了哦

有证书的大佬，没有Mac，用虚拟机build太费劲了

**Comment by LunWhale** [comment]
或者，大佬可以告诉我app store上架的地区吗，我在美区，国区，澳区都没找到
